config/routes.rb
Rails.application.routes.draw do

 devise_for :users
 root to: 'homes#top'

 resources :books, only: [:new, :create, :index, :show, :destroy,:edit,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
 get "/home/about" => "homes#about", as: "about"
  # about GET    /home/about(.:format)
 resources :users, only: [:show, :edit, :update,:index]
 # patch 'lists/:id' => 'lists#update', as: 'update_list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, {presence: true,length: {maximum: 200}}
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #has_one_attached :image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image
  
  
  
   validates :name, presence: true, length: {minimum: 2,maximum: 20}, uniqueness: true
  # validates :content, {presence: true, lengh: {maximum: 140}}
   validates :introduction, length: {maximum: 50}
  # validates :image, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインページに誘導される
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "successfully"
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "successfully"
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def post_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
     @book = Book.new
  end
  
   # 投稿データの保存
  def create
    @booknew = Book.new(book_params)
    @booknew.user_id = current_user.id
    if @booknew.save
      flash[:notice] = "successfully"
      redirect_to book_path(@booknew),method: :get
    else
      @user = current_user
      @books =Book.all
      
      flash[:notice] = "error"
      render :index
      # 上の違う
    end
  end

  def index
    @books =Book.all
    @user = current_user
    @booknew = Book.new
   
  end

  def show
    @book = Book.find(params[:id])
    @user= @book.user
    @books = Book.all
    @booknew = Book.new
    @post_comment = BookComment.new
  end
  
  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)  
    @book.user_id = current_user.id
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id),method: :get
  else
    flash[:notice] = "error"
    render :edit
  end
  end

  def edit
    @book = Book.find(params[:id])
    @user= @book.user
    if @user==current_user
      flash[:notice] = "successfully"
      @book = Book.find(params[:id])
    else
      @booknew = Book.new
      redirect_to books_path,method: :get
    end
    
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
   # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)if params[:book].present?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # なぜ?
    @user=current_user
  end
  
  def about 
    
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  # indexはいらないの？
  
  def index
     @user = current_user
     @books =Book.all
     @users=User.all
     @booknew = Book.new
    
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @booknew = Book.new
  end

  def edit
    @user = User.find(params[:id])
  if @user==current_user
    flash[:notice] = "successfully"
  else
    @user=current_user
    redirect_to user_path(@user.id)  
  end
  end
  
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)  
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
      <!--<img src="https://bookers-level2.herokuapp.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1hSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd39249e0381ea04ed630cc1a6958df9bc947839/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVdscGFRPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--4a929dbc7794f3c4610ba9ba5402762ad9cd1a14/default-image.jpg">-->
      <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
    <!--下の(@user)をつけなくてもshowはいけたのに、indexはできないなぜ？-->
    <%=link_to edit_user_path(user),class:"btn btn-outline-secondary" do%>
    <i class="fas fa-user-cog" aria-hidden="true"></i>
    <%end%>

</div>



<!--creatかupdateを自動で判断してくれる-->
 <%= form_with model: booknew do |f| %>
    <h2 class="mt-3">New book</h2>
      <%#= f.file_field :image, accept: "image/*" %>
    Title<br>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
   <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
  <% end %>

</div>

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>Editing Book</h2>

<%= form_with model: @book do |f| %>
  <label for="inputName">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:"title"%>
  <label for="inputName">Opinion</label>
  <%= f.text_field :body, autofocus: true, id:"inputName", placeholder:"body"%>

  <%# f.submit "Update book" %>

  <div class="form-group">
    <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
  </div>

<% end %>

    <%= link_to "Show", book_path(@book) %>


<a class="back" href="/books">Back</a>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<% if @booknew.errors.any? %>
  <%= @booknew.errors.count %>件のエラーが発生しました
  <ul>
    <% @booknew.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p id="notice"></p>
　<div class="container px-5 px-sm-0">
  <div class="row">
<!-- ユーザーの投稿一覧 -->
<%= render 'books/list', books: @books,user: @user,book: @book,booknew: @booknew%>
<!--@user,@books,@book-->


</form>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tr>
    <td>  <%= link_to user_path(book.id) do %>
     <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %></td>
 <td>  <%= link_to book_path(book.id) do %>
 <%= book.title %>
 <% end %></td>
     <td> <%= book.body %></td>
     
     <!--いいねしているか-->
     <td><% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fa-regular fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
</td>
   
     
   <td>
     <p><%= link_to "#{book.book_comments.count} コメント", books_path(book.id) %></p> 
   </td>
 
  </tr>
  <% end %>

  <tbody>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>

  <% if @booknew.errors.any? %>
  <%= @booknew.errors.count %>件のエラーが発生しました
  <ul>
    <% @bookenw.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @book do |f| %>
    <h4>画像</h4>
      <%#= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :title %>
    <h4>説明</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<p id="notice"></p>
　<div class="container px-5 px-sm-0">
  <div class="row">
<!-- ユーザーの投稿一覧 -->
<%= render 'books/list', books: @books,user: @user,book: @book,booknew: @booknew%>
</form>

<%# if user_signed_in? %>
<!--もしログインしたユーザーならば-->
<%if @user==current_user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>
<!--ここにform_with使ったらエラーが出る-->

  <tr>
    <td>  <%= link_to user_path(@user.id) do %>
     <%= image_tag @user.get_profile_image(100,100) %><br>
     <%= @user.name %>
  <% end %></td>
 <td> <%= @book.title %></td>
     <td><%=  @book.body %></td>
     <td>
       <!--<a class="btn btn-sm btn-success edit_book_87387" href="/books/87387/edit">Edit</a>-->
        <%=link_to edit_book_path(@book),class:"btn btn-sm btn-success" do%>
    Edit
        <%end%>
       </td>
     <td>
       <%= link_to "Destroy", book_path(@book), class:"text-dark", method: :delete %>
     </td>
     <td><%=  @book.body %></td>
     
      <td><% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fa-regular fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
  <% end %>
</td>
<td><p>コメント件数：<%= @book.book_comments.count %></p></td>


  </tr>
</table>
<div>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>
    <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
     <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
    <% end %>

  <% end %>
</div>

<div>
  <%= form_with model: [@book, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>



</div>


<% else %>
<!--もしログインしたユーザーと違うならば-->
<!--上のプログラムのedit　とdestroyを消す-->
<div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>
<!--ここにform_with使ったらエラーが出る-->
  <tr>
  <td>  <%= link_to user_path(@user.id) do %>
     <%= image_tag @user.get_profile_image(100,100) %><br>
     <%= @user.name %>
   <% end %>
  </td>
  <td>
      <%= link_to book_path(@book.id) do %>
         <%= @book.title %>
      <% end %>
  </td>
  <td><%=@book.body %></td>
  
  
   <td><% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fa-regular fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
  <% end %>
</td>
     
      <td><p>コメント件数：<%= @book.book_comments.count %></p></td>

    </tr>
</table>
<div>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>
    <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
     <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
    <% end %>

  <% end %>
</div>

<div>
  <%= form_with model: [@book, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信" %>
  <% end %>
</div>

</div>
<% end %>


</div>
</div>

app/views/homes/about.html.erb
<body>
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

  

</body>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/d004fc78e0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>




   <body class="d-flex flex-column vh-100">
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
             <li>
            <%=link_to user_path(current_user),method: :get,class:"nav-link text-light" do%>
            <i class="fas fa-home" aria-hidden="true"></i>Home
            <%end%>
            </li>
            
             <li>
            <%=link_to users_path,method: :get,class:"nav-link text-light" do%>
            <i class="fas fa-users" aria-hidden="true"></i>Users
            <%end%>
            </li>
          
          
          <li>
              <%=link_to books_path,method: :get,class:"nav-link text-light" do%>
                <i class="fas fa-book-open" aria-hidden="true"></i> Books
                <%end%>
            </li>
            
          <li>
            <%=link_to destroy_user_session_path,method: :delete,class:"nav-link text-light" do%>
            <i class="fas fa-sign-out-alt" aria-hidden="true"></i>logout
            <%end%>
          </li>
          
        <% else %>
            <li>
              <a class="nav-link text-light" href="/">
                <i class="fas fa-home" aria-hidden="true"></i> Home
              </a>
            </li>
            <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link" aria-hidden="true"></i> About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus" aria-hidden="true"></i>sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt" aria-hidden="true"></i> login
            </a>          
          </li>
  
        <% end %>
          

        </ul>
      </div>
    </div>
  </nav>
</header>
<main>
  <%= yield %>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputName">introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"introduction"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"></p>
　<div class="container px-5 px-sm-0">
  <div class="row">
<!-- ユーザーの投稿一覧 -->
<%= render 'books/list', books: @books,user: @user,book: @book,booknew: @booknew%>
<!--@user,@books,@book-->


</form>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>imges</th>
      <th>name</th>
      <th></th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tr>
    <td> 
     <%= image_tag user.get_profile_image(100,100) %>
  </td>
  <td> <%= user.name %></td>
     <td><%= link_to user_path(user.id) do %>
        Show
         <% end %>
    </td>
  </tr>
  <% end %>

  <tbody>
  </tbody>
</table>
</div>




</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
　<div class="container px-5 px-sm-0">
  <div class="row">
<!-- ユーザーの投稿一覧 -->
<%= render 'books/list', books: @books,user: @user,book: @book,booknew: @booknew%>
<!--@user,@books,@book-->


</form>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tr>
    <td>  <%= link_to user_path(@user.id) do %>
     <%= image_tag @user.get_profile_image(100,100) %>
  <% end %></td>
 <!--<td> title：<%#= book.title %></td>-->

 <td>
  <%= link_to book_path(book.id),method:  :get do %>
     <%= book.title %>
  <% end %>
  </td>


     <td> <%= book.body%></td>
     
      <!--いいねしているか-->
     <td><% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fa-regular fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
</td>
   
     
   <td>
     <p><%= link_to "#{book.book_comments.count} コメント", books_path(book.id) %></p> 
   </td>
     
  </tr>
  <% end %>



  <tbody>
  </tbody>
</table>
</div>
</div>
</div>